sudo: false
language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
cache:
  directories:
    - "node_modules"
install:
  - npm install ---silent
script:
  - "npm run test"
  - "npm run build-storybook"
  - "npm run build"
